title: "Bhawna Dixit"
description: "Molecular modeling, protein dynamics, and AI for structural biology"
theme: minima

# Optional but nice
author:
  name: "Bhawna Dixit"
  email: "dixitbhawna16@gmail.com

# Social links (fill what you use)
github_username: "https://github.com/Bhawnadixit"
linkedin_username: "https://www.linkedin.com/in/bhawna-dixit/" 
orcid: "0000-0003-4718-4911"

# Build settings
markdown: kramdown



